# Generated by Django 5.1.4 on 2025-04-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_date_alter_task_finishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finishDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
