# Generated by Django 5.1.4 on 2025-06-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_task_finishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=254, null=True),
        ),
    ]
